/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.notify.conf 10110 2004-04-15 12:29:19Z dts12 $
 */
#ifndef INGRES_H
#define INGRES_H

/*
 * function declarations 
 */
int             send_logmon_trap(void);
int             send_procmon_trap(void);

#endif                          /* INGRES_H */
