/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-oids.m2c 12855 2005-09-27 15:56:08Z rstory $
 *
 * $Id:$
 */
#ifndef DMFTABLE_OIDS_H
#define DMFTABLE_OIDS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     * column number definitions for table dmfTable 
     */
#define DMFTABLE_OID              1,3,6,1,4,1,757,5,1,1

#define COLUMN_SERVER         1

#define COLUMN_PAGESIZE         2

#define COLUMN_FORCECOUNT         3

#define COLUMN_IOWAITCOUNT         4

#define COLUMN_GROUPBUFFERREADCOUNT         5

#define COLUMN_GROUPBUFFERWRITECOUNT         6

#define COLUMN_FIXCOUNT         7

#define COLUMN_UNFIXCOUNT         8

#define COLUMN_READCOUNT         9

#define COLUMN_WRITECOUNT         10

#define COLUMN_HITCOUNT         11

#define COLUMN_DIRTYUNFIXCOUNT         12

#define COLUMN_PAGESSTILLVALID         13

#define COLUMN_PAGESINVALID         14

#define COLUMN_BUFFERCOUNT         15

#define COLUMN_PAGEBUFFERCOUNT         16

#define COLUMN_FLIMIT         17

#define COLUMN_MLIMIT         18

#define COLUMN_WBSTART         19

#define COLUMN_WBEND         20

#define COLUMN_HASHBUCKETCOUNT         21

#define COLUMN_GROUPBUFFERCOUNT         22

#define COLUMN_GROUPBUFFERSIZE         23

#define COLUMN_CACHESTATUS         24

#define COLUMN_FREEBUFFERCOUNT         25

#define COLUMN_FREEBUFFERWAITERS         26

#define COLUMN_FIXEDBUFFERCOUNT         27

#define COLUMN_MODIFIEDBUFFERCOUNT         28

#define COLUMN_FREEGROUPBUFFERCOUNT         29

#define COLUMN_FIXEDGROUPBUFFERCOUNT         30

#define COLUMN_MODIFIEDGROUPBUFFERCOUNT         31


#define DMFTABLE_MIN_COL   COLUMN_SERVER
#define DMFTABLE_MAX_COL   COLUMN_MODIFIEDGROUPBUFFERCOUNT



#ifdef __cplusplus
}
#endif
#endif                          /* DMFTABLE_OIDS_H */
