/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef INGSTAT_H
#define INGSTAT_H

/*
 * function declarations 
 */

extern int ingstat(char * command, char * str, char * value);
extern int getval(char * regex,char * input,char * value);

/*
 * includes
 */

#include "ingstat.c"

#endif                          /* LOGSTAT_H */
