/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef LOCKSTAT_H
#define LOCKSTAT_H

/*
 * function declarations 
 */
void            init_lockstat(void);
Netsnmp_Node_Handler handle_lockWait;
Netsnmp_Node_Handler handle_deadlock;
Netsnmp_Node_Handler handle_highwaterLBK;
Netsnmp_Node_Handler handle_highwaterSBK;
Netsnmp_Node_Handler handle_highwaterRBK;
Netsnmp_Node_Handler handle_totalLocks;
Netsnmp_Node_Handler handle_totalResources;
Netsnmp_Node_Handler handle_locksPerTransaction;
Netsnmp_Node_Handler handle_locksInUse;
Netsnmp_Node_Handler handle_resourcesInUse;
Netsnmp_Node_Handler handle_lockListsInUse;
Netsnmp_Node_Handler handle_totalLockLists;

#endif                          /* LOCKSTAT_H */
