/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $
 *
 * $Id:$
 */
#ifndef DMFTABLE_DATA_ACCESS_H
#define DMFTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     *********************************************************************
     * function declarations
     */

    /*
     *********************************************************************
     * Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dmfTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * INGRES-MIB::dmfTable is subid 1 of imadb.
     * Its status is Current.
     * OID: .1.3.6.1.4.1.757.5.1.1, length: 10
     */


    int             dmfTable_init_data(dmfTable_registration *
                                       dmfTable_reg);


    /*
     * TODO:180:o: Review dmfTable cache timeout.
     * The number of seconds before the cache times out
     */
#define DMFTABLE_CACHE_TIMEOUT   60

    void            dmfTable_container_init(netsnmp_container **
                                            container_ptr_ptr,
                                            netsnmp_cache * cache);
    void            dmfTable_container_shutdown(netsnmp_container *
                                                container_ptr);

    int             dmfTable_container_load(netsnmp_container * container);
    void            dmfTable_container_free(netsnmp_container * container);

    int             dmfTable_cache_load(netsnmp_container * container);
    void            dmfTable_cache_free(netsnmp_container * container);

    /*
     ***************************************************
     ***             START EXAMPLE CODE              ***
     ***---------------------------------------------***/
    /*
     *********************************************************************
     * Since we have no idea how you really access your data, we'll go with
     * a worst case example: a flat text file.
     */
#define MAX_LINE_SIZE 256
    /*
     ***---------------------------------------------***
     ***              END  EXAMPLE CODE              ***
     ***************************************************/
    int             dmfTable_row_prep(dmfTable_rowreq_ctx * rowreq_ctx);



#ifdef __cplusplus
}
#endif
#endif                          /* DMFTABLE_DATA_ACCESS_H */
