/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $ 
 *
 * $Id:$
 */
/** \page MFD helper for dmfTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/*
 * standard Net-SNMP includes 
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/*
 * include our parent header 
 */
#include "dmfTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "dmfTable_interface.h"

oid             dmfTable_oid[] = { DMFTABLE_OID };
int             dmfTable_oid_size = OID_LENGTH(dmfTable_oid);

dmfTable_registration dmfTable_user_context;

void            initialize_table_dmfTable(void);
void            shutdown_table_dmfTable(void);


/**
 * Initializes the dmfTable module
 */
void
init_dmfTable(void)
{
    DEBUGMSGTL(("verbose:dmfTable:init_dmfTable", "called\n"));

    /*
     * TODO:300:o: Perform dmfTable one-time module initialization.
     */

    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("dmfTable"))
        initialize_table_dmfTable();

}                               /* init_dmfTable */

/**
 * Shut-down the dmfTable module (agent is exiting)
 */
void
shutdown_dmfTable(void)
{
    if (should_init("dmfTable"))
        shutdown_table_dmfTable();

}

/**
 * Initialize the table dmfTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_dmfTable(void)
{
    dmfTable_registration *user_context;
    u_long          flags;

    DEBUGMSGTL(("verbose:dmfTable:initialize_table_dmfTable", "called\n"));

    /*
     * TODO:301:o: Perform dmfTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize dmfTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("dmfTable", NULL, NULL);

    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;

    /*
     * call interface initialization code
     */
    _dmfTable_initialize_interface(user_context, flags);
}                               /* initialize_table_dmfTable */

/**
 * Shutdown the table dmfTable 
 */
void
shutdown_table_dmfTable(void)
{
    /*
     * call interface shutdown code
     */
    _dmfTable_shutdown_interface(&dmfTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
dmfTable_rowreq_ctx_init(dmfTable_rowreq_ctx * rowreq_ctx,
                         void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:dmfTable:dmfTable_rowreq_ctx_init", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:210:o: |-> Perform extra dmfTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
}                               /* dmfTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void
dmfTable_rowreq_ctx_cleanup(dmfTable_rowreq_ctx * rowreq_ctx)
{
    DEBUGMSGTL(("verbose:dmfTable:dmfTable_rowreq_ctx_cleanup",
                "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:211:o: |-> Perform extra dmfTable rowreq cleanup.
     */
}                               /* dmfTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
dmfTable_pre_request(dmfTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:dmfTable:dmfTable_pre_request", "called\n"));

    /*
     * TODO:510:o: Perform dmfTable pre-request actions.
     */

    return MFD_SUCCESS;
}                               /* dmfTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
dmfTable_post_request(dmfTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:dmfTable:dmfTable_post_request", "called\n"));

    /*
     * TODO:511:o: Perform dmfTable post-request actions.
     */

    return MFD_SUCCESS;
}                               /* dmfTable_post_request */


/** @{ */
