/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 15899 $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef DMFTABLE_INTERFACE_H
#define DMFTABLE_INTERFACE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include "dmfTable.h"


    /*
     ********************************************************************
     * Table declarations
     */

    /*
     * PUBLIC interface initialization routine 
     */
    void            _dmfTable_initialize_interface(dmfTable_registration *
                                                   user_ctx, u_long flags);
    void            _dmfTable_shutdown_interface(dmfTable_registration *
                                                 user_ctx);

    dmfTable_registration *dmfTable_registration_get(void);

    dmfTable_registration *dmfTable_registration_set(dmfTable_registration
                                                     * newreg);

    netsnmp_container *dmfTable_container_get(void);
    int             dmfTable_container_size(void);

    dmfTable_rowreq_ctx *dmfTable_allocate_rowreq_ctx(void *);
    void            dmfTable_release_rowreq_ctx(dmfTable_rowreq_ctx *
                                                rowreq_ctx);

    int             dmfTable_index_to_oid(netsnmp_index * oid_idx,
                                          dmfTable_mib_index * mib_idx);
    int             dmfTable_index_from_oid(netsnmp_index * oid_idx,
                                            dmfTable_mib_index * mib_idx);

    /*
     * access to certain internals. use with caution!
     */
    void            dmfTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif
#endif                          /* DMFTABLE_INTERFACE_H */
/** @} */
