/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $
 *
 * $Id:$
 *
 * @file dmfTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef DMFTABLE_DATA_GET_H
#define DMFTABLE_DATA_GET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * GET function declarations
     */

    /*
     *********************************************************************
     * GET Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dmfTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * INGRES-MIB::dmfTable is subid 1 of imadb.
     * Its status is Current.
     * OID: .1.3.6.1.4.1.757.5.1.1, length: 10
     */
    /*
     * indexes
     */

    int             forceCount_get(dmfTable_rowreq_ctx * rowreq_ctx,
                                   long *forceCount_val_ptr);
    int             ioWaitCount_get(dmfTable_rowreq_ctx * rowreq_ctx,
                                    long *ioWaitCount_val_ptr);
    int             groupBufferReadCount_get(dmfTable_rowreq_ctx *
                                             rowreq_ctx,
                                             long
                                             *groupBufferReadCount_val_ptr);
    int             groupBufferWriteCount_get(dmfTable_rowreq_ctx *
                                              rowreq_ctx,
                                              long
                                              *groupBufferWriteCount_val_ptr);
    int             fixCount_get(dmfTable_rowreq_ctx * rowreq_ctx,
                                 long *fixCount_val_ptr);
    int             unfixCount_get(dmfTable_rowreq_ctx * rowreq_ctx,
                                   long *unfixCount_val_ptr);
    int             readCount_get(dmfTable_rowreq_ctx * rowreq_ctx,
                                  long *readCount_val_ptr);
    int             writeCount_get(dmfTable_rowreq_ctx * rowreq_ctx,
                                   long *writeCount_val_ptr);
    int             hitCount_get(dmfTable_rowreq_ctx * rowreq_ctx,
                                 long *hitCount_val_ptr);
    int             dirtyUnfixCount_get(dmfTable_rowreq_ctx * rowreq_ctx,
                                        long *dirtyUnfixCount_val_ptr);
    int             pagesStillValid_get(dmfTable_rowreq_ctx * rowreq_ctx,
                                        long *pagesStillValid_val_ptr);
    int             pagesInvalid_get(dmfTable_rowreq_ctx * rowreq_ctx,
                                     long *pagesInvalid_val_ptr);
    int             bufferCount_get(dmfTable_rowreq_ctx * rowreq_ctx,
                                    long *bufferCount_val_ptr);
    int             pageBufferCount_get(dmfTable_rowreq_ctx * rowreq_ctx,
                                        long *pageBufferCount_val_ptr);
    int             fLimit_get(dmfTable_rowreq_ctx * rowreq_ctx,
                               long *fLimit_val_ptr);
    int             mLimit_get(dmfTable_rowreq_ctx * rowreq_ctx,
                               long *mLimit_val_ptr);
    int             wbStart_get(dmfTable_rowreq_ctx * rowreq_ctx,
                                long *wbStart_val_ptr);
    int             wbEnd_get(dmfTable_rowreq_ctx * rowreq_ctx,
                              long *wbEnd_val_ptr);
    int             hashBucketCount_get(dmfTable_rowreq_ctx * rowreq_ctx,
                                        long *hashBucketCount_val_ptr);
    int             groupBufferCount_get(dmfTable_rowreq_ctx * rowreq_ctx,
                                         long *groupBufferCount_val_ptr);
    int             groupBufferSize_get(dmfTable_rowreq_ctx * rowreq_ctx,
                                        long *groupBufferSize_val_ptr);
    int             cacheStatus_get(dmfTable_rowreq_ctx * rowreq_ctx,
                                    long *cacheStatus_val_ptr);
    int             freeBufferCount_get(dmfTable_rowreq_ctx * rowreq_ctx,
                                        long *freeBufferCount_val_ptr);
    int             freeBufferWaiters_get(dmfTable_rowreq_ctx * rowreq_ctx,
                                          long *freeBufferWaiters_val_ptr);
    int             fixedBufferCount_get(dmfTable_rowreq_ctx * rowreq_ctx,
                                         long *fixedBufferCount_val_ptr);
    int             modifiedBufferCount_get(dmfTable_rowreq_ctx *
                                            rowreq_ctx,
                                            long
                                            *modifiedBufferCount_val_ptr);
    int             freeGroupBufferCount_get(dmfTable_rowreq_ctx *
                                             rowreq_ctx,
                                             long
                                             *freeGroupBufferCount_val_ptr);
    int             fixedGroupBufferCount_get(dmfTable_rowreq_ctx *
                                              rowreq_ctx,
                                              long
                                              *fixedGroupBufferCount_val_ptr);
    int             modifiedGroupBufferCount_get(dmfTable_rowreq_ctx *
                                                 rowreq_ctx,
                                                 long
                                                 *modifiedGroupBufferCount_val_ptr);


    int             dmfTable_indexes_set_tbl_idx(dmfTable_mib_index *
                                                 tbl_idx,
                                                 char *server_val_ptr,
                                                 size_t server_val_ptr_len,
                                                 long pagesize_val);
    int             dmfTable_indexes_set(dmfTable_rowreq_ctx * rowreq_ctx,
                                         char *server_val_ptr,
                                         size_t server_val_ptr_len,
                                         long pagesize_val);




#ifdef __cplusplus
}
#endif
#endif                          /* DMFTABLE_DATA_GET_H */
/** @} */
