/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $ 
 *
 * $Id:$
 */
/*
 * standard Net-SNMP includes 
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/*
 * include our parent header 
 */
#include "dmfTable.h"


#include "dmfTable_data_access.h"

/** @ingroup interface
 * @addtogroup data_access data_access: Routines to access data
 *
 * These routines are used to locate the data used to satisfy
 * requests.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dmfTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * INGRES-MIB::dmfTable is subid 1 of imadb.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.757.5.1.1, length: 10
 */

/**
 * initialization for dmfTable data access
 *
 * This function is called during startup to allow you to
 * allocate any resources you need for the data table.
 *
 * @param dmfTable_reg
 *        Pointer to dmfTable_registration
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : unrecoverable error.
 */
int
dmfTable_init_data(dmfTable_registration * dmfTable_reg)
{
    DEBUGMSGTL(("verbose:dmfTable:dmfTable_init_data", "called\n"));

    /*
     * TODO:303:o: Initialize dmfTable data.
     */
    /*
     ***************************************************
     ***             START EXAMPLE CODE              ***
     ***---------------------------------------------***/
    /*
     * if you are the sole writer for the file, you could
     * open it here. However, as stated earlier, we are assuming
     * the worst case, which in this case means that the file is
     * written to by someone else, and might not even exist when
     * we start up. So we can't do anything here.
     */
    /*
     ***---------------------------------------------***
     ***              END  EXAMPLE CODE              ***
     ***************************************************/

    return MFD_SUCCESS;
}                               /* dmfTable_init_data */

/**
 * container overview
 *
 */

/**
 * container initialization
 *
 * @param container_ptr_ptr A pointer to a container pointer. If you
 *        create a custom container, use this parameter to return it
 *        to the MFD helper. If set to NULL, the MFD helper will
 *        allocate a container for you.
 * @param  cache A pointer to a cache structure. You can set the timeout
 *         and other cache flags using this pointer.
 *
 *  This function is called at startup to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases. If no custom
 *  container is allocated, the MFD code will create one for your.
 *
 *  This is also the place to set up cache behavior. The default, to
 *  simply set the cache timeout, will work well with the default
 *  container. If you are using a custom container, you may want to
 *  look at the cache helper documentation to see if there are any
 *  flags you want to set.
 *
 * @remark
 *  This would also be a good place to do any initialization needed
 *  for you data source. For example, opening a connection to another
 *  process that will supply the data, opening a database, etc.
 */
void
dmfTable_container_init(netsnmp_container ** container_ptr_ptr,
                        netsnmp_cache * cache)
{
    DEBUGMSGTL(("verbose:dmfTable:dmfTable_container_init", "called\n"));

    if (NULL == container_ptr_ptr) {
        snmp_log(LOG_ERR,
                 "bad container param to dmfTable_container_init\n");
        return;
    }

    /*
     * For advanced users, you can use a custom container. If you
     * do not create one, one will be created for you.
     */
    *container_ptr_ptr = NULL;

    if (NULL == cache) {
        snmp_log(LOG_ERR, "bad cache param to dmfTable_container_init\n");
        return;
    }

    /*
     * TODO:345:A: Set up dmfTable cache properties.
     *
     * Also for advanced users, you can set parameters for the
     * cache. Do not change the magic pointer, as it is used
     * by the MFD helper. To completely disable caching, set
     * cache->enabled to 0.
     */
    cache->timeout = DMFTABLE_CACHE_TIMEOUT;    /* seconds */
}                               /* dmfTable_container_init */

/**
 * container shutdown
 *
 * @param container_ptr A pointer to the container.
 *
 *  This function is called at shutdown to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases.
 *
 *  This function is called before dmfTable_container_free().
 *
 * @remark
 *  This would also be a good place to do any cleanup needed
 *  for you data source. For example, closing a connection to another
 *  process that supplied the data, closing a database, etc.
 */
void
dmfTable_container_shutdown(netsnmp_container * container_ptr)
{
    DEBUGMSGTL(("verbose:dmfTable:dmfTable_container_shutdown",
                "called\n"));

    if (NULL == container_ptr) {
        snmp_log(LOG_ERR, "bad params to dmfTable_container_shutdown\n");
        return;
    }

}                               /* dmfTable_container_shutdown */

/**
 * load initial data
 *
 * TODO:350:M: Implement dmfTable data load
 * This function will also be called by the cache helper to load
 * the container again (after the container free function has been
 * called to free the previous contents).
 *
 * @param container container to which items should be inserted
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_RESOURCE_UNAVAILABLE : Can't access data source
 * @retval MFD_ERROR                : other error.
 *
 *  This function is called to load the index(es) (and data, optionally)
 *  for the every row in the data set.
 *
 * @remark
 *  While loading the data, the only important thing is the indexes.
 *  If access to your data is cheap/fast (e.g. you have a pointer to a
 *  structure in memory), it would make sense to update the data here.
 *  If, however, the accessing the data invovles more work (e.g. parsing
 *  some other existing data, or peforming calculations to derive the data),
 *  then you can limit yourself to setting the indexes and saving any
 *  information you will need later. Then use the saved information in
 *  dmfTable_row_prep() for populating data.
 *
 * @note
 *  If you need consistency between rows (like you want statistics
 *  for each row to be from the same time frame), you should set all
 *  data here.
 *
 */
int
dmfTable_container_load(netsnmp_container * container)
{
    dmfTable_rowreq_ctx *rowreq_ctx;
    size_t          count = 0;

    /*
     * temporary storage for index values
     */
    /*
     * server(1)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
     */
        /** 128 - 1(entry) - 1(col) - 1(other indexes) = 113 */
    char            server[113];
    size_t          server_len;
    /*
     * pagesize(2)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
     */
    long            pagesize;


    /*
     * this example code is based on a data source that is a
     * text file to be read and parsed.
     */
    FILE           *filep;
    char            line[MAX_LINE_SIZE];

    DEBUGMSGTL(("verbose:dmfTable:dmfTable_container_load", "called\n"));

    /*
     ***************************************************
     ***             START EXAMPLE CODE              ***
     ***---------------------------------------------***/
    /*
     * open our data file.
     */
    filep = fopen("/etc/dummy.conf", "r");
    if (NULL == filep) {
        return MFD_RESOURCE_UNAVAILABLE;
    }

    /*
     ***---------------------------------------------***
     ***              END  EXAMPLE CODE              ***
     ***************************************************/
    /*
     * TODO:351:M: |-> Load/update data in the dmfTable container.
     * loop over your dmfTable data, allocate a rowreq context,
     * set the index(es) [and data, optionally] and insert into
     * the container.
     */
    while (1) {
        /*
         ***************************************************
         ***             START EXAMPLE CODE              ***
         ***---------------------------------------------***/
        /*
         * get a line (skip blank lines)
         */
        do {
            if (!fgets(line, sizeof(line), filep)) {
                /*
                 * we're done 
                 */
                fclose(filep);
                filep = NULL;
            }
        } while (filep && (line[0] == '\n'));

        /*
         * check for end of data
         */
        if (NULL == filep)
            break;

        /*
         * parse line into variables
         */
        /*
         ***---------------------------------------------***
         ***              END  EXAMPLE CODE              ***
         ***************************************************/

        /*
         * TODO:352:M: |   |-> set indexes in new dmfTable rowreq context.
         * data context will be set from the param (unless NULL,
         *      in which case a new data context will be allocated)
         */
        rowreq_ctx = dmfTable_allocate_rowreq_ctx(NULL);
        if (NULL == rowreq_ctx) {
            snmp_log(LOG_ERR, "memory allocation failed\n");
            return MFD_RESOURCE_UNAVAILABLE;
        }
        if (MFD_SUCCESS !=
            dmfTable_indexes_set(rowreq_ctx, server, server_len,
                                 pagesize)) {
            snmp_log(LOG_ERR,
                     "error setting index while loading "
                     "dmfTable data.\n");
            dmfTable_release_rowreq_ctx(rowreq_ctx);
            continue;
        }

        /*
         * TODO:352:r: |   |-> populate dmfTable data context.
         * Populate data context here. (optionally, delay until row prep)
         */
        /*
         * TRANSIENT or semi-TRANSIENT data:
         * copy data or save any info needed to do it in row_prep.
         */
        /*
         * setup/save data for forceCount
         * forceCount(3)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.forceCount = forceCount;

        /*
         * setup/save data for ioWaitCount
         * ioWaitCount(4)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.ioWaitCount = ioWaitCount;

        /*
         * setup/save data for groupBufferReadCount
         * groupBufferReadCount(5)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.groupBufferReadCount = groupBufferReadCount;

        /*
         * setup/save data for groupBufferWriteCount
         * groupBufferWriteCount(6)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.groupBufferWriteCount = groupBufferWriteCount;

        /*
         * setup/save data for fixCount
         * fixCount(7)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.fixCount = fixCount;

        /*
         * setup/save data for unfixCount
         * unfixCount(8)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.unfixCount = unfixCount;

        /*
         * setup/save data for readCount
         * readCount(9)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.readCount = readCount;

        /*
         * setup/save data for writeCount
         * writeCount(10)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.writeCount = writeCount;

        /*
         * setup/save data for hitCount
         * hitCount(11)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.hitCount = hitCount;

        /*
         * setup/save data for dirtyUnfixCount
         * dirtyUnfixCount(12)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.dirtyUnfixCount = dirtyUnfixCount;

        /*
         * setup/save data for pagesStillValid
         * pagesStillValid(13)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.pagesStillValid = pagesStillValid;

        /*
         * setup/save data for pagesInvalid
         * pagesInvalid(14)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.pagesInvalid = pagesInvalid;

        /*
         * setup/save data for bufferCount
         * bufferCount(15)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.bufferCount = bufferCount;

        /*
         * setup/save data for pageBufferCount
         * pageBufferCount(16)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.pageBufferCount = pageBufferCount;

        /*
         * setup/save data for fLimit
         * fLimit(17)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.fLimit = fLimit;

        /*
         * setup/save data for mLimit
         * mLimit(18)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.mLimit = mLimit;

        /*
         * setup/save data for wbStart
         * wbStart(19)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.wbStart = wbStart;

        /*
         * setup/save data for wbEnd
         * wbEnd(20)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.wbEnd = wbEnd;

        /*
         * setup/save data for hashBucketCount
         * hashBucketCount(21)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.hashBucketCount = hashBucketCount;

        /*
         * setup/save data for groupBufferCount
         * groupBufferCount(22)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.groupBufferCount = groupBufferCount;

        /*
         * setup/save data for groupBufferSize
         * groupBufferSize(23)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.groupBufferSize = groupBufferSize;

        /*
         * setup/save data for cacheStatus
         * cacheStatus(24)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.cacheStatus = cacheStatus;

        /*
         * setup/save data for freeBufferCount
         * freeBufferCount(25)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.freeBufferCount = freeBufferCount;

        /*
         * setup/save data for freeBufferWaiters
         * freeBufferWaiters(26)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.freeBufferWaiters = freeBufferWaiters;

        /*
         * setup/save data for fixedBufferCount
         * fixedBufferCount(27)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.fixedBufferCount = fixedBufferCount;

        /*
         * setup/save data for modifiedBufferCount
         * modifiedBufferCount(28)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.modifiedBufferCount = modifiedBufferCount;

        /*
         * setup/save data for freeGroupBufferCount
         * freeGroupBufferCount(29)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.freeGroupBufferCount = freeGroupBufferCount;

        /*
         * setup/save data for fixedGroupBufferCount
         * fixedGroupBufferCount(30)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.fixedGroupBufferCount = fixedGroupBufferCount;

        /*
         * setup/save data for modifiedGroupBufferCount
         * modifiedGroupBufferCount(31)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.modifiedGroupBufferCount =
            modifiedGroupBufferCount;


        /*
         * insert into table container
         */
        CONTAINER_INSERT(container, rowreq_ctx);
        ++count;
    }

    /*
     ***************************************************
     ***             START EXAMPLE CODE              ***
     ***---------------------------------------------***/
    if (NULL != filep)
        fclose(filep);
    /*
     ***---------------------------------------------***
     ***              END  EXAMPLE CODE              ***
     ***************************************************/

    DEBUGMSGT(("verbose:dmfTable:dmfTable_container_load",
               "inserted %d records\n", count));

    return MFD_SUCCESS;
}                               /* dmfTable_container_load */

/**
 * container clean up
 *
 * @param container container with all current items
 *
 *  This optional callback is called prior to all
 *  item's being removed from the container. If you
 *  need to do any processing before that, do it here.
 *
 * @note
 *  The MFD helper will take care of releasing all the row contexts.
 *
 */
void
dmfTable_container_free(netsnmp_container * container)
{
    DEBUGMSGTL(("verbose:dmfTable:dmfTable_container_free", "called\n"));

    /*
     * TODO:380:M: Free dmfTable container data.
     */
}                               /* dmfTable_container_free */

/**
 * prepare row for processing.
 *
 *  When the agent has located the row for a request, this function is
 *  called to prepare the row for processing. If you fully populated
 *  the data context during the index setup phase, you may not need to
 *  do anything.
 *
 * @param rowreq_ctx pointer to a context.
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 */
int
dmfTable_row_prep(dmfTable_rowreq_ctx * rowreq_ctx)
{
    DEBUGMSGTL(("verbose:dmfTable:dmfTable_row_prep", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:390:o: Prepare row for request.
     * If populating row data was delayed, this is the place to
     * fill in the row for this request.
     */

    return MFD_SUCCESS;
}                               /* dmfTable_row_prep */

/** @} */
