/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef INGRES_H
#define INGRES_H

/*
 * function declarations 
 */
void            init_ingres(void);
Netsnmp_Node_Handler handle_logWritersBusy;
Netsnmp_Node_Handler handle_maxWriteQueueLength;
Netsnmp_Node_Handler handle_maxWriteQueueCount;
Netsnmp_Node_Handler handle_logWaits;
Netsnmp_Node_Handler handle_splitBuffer;
Netsnmp_Node_Handler handle_freeBuffer;
Netsnmp_Node_Handler handle_lastBuf;
Netsnmp_Node_Handler handle_logFullStall;
Netsnmp_Node_Handler handle_lockWait;
Netsnmp_Node_Handler handle_deadlock;
Netsnmp_Node_Handler handle_highwaterLBK;
Netsnmp_Node_Handler handle_highwaterSBK;
Netsnmp_Node_Handler handle_highwaterRBK;
Netsnmp_Node_Handler handle_totalLocks;
Netsnmp_Node_Handler handle_totalResources;
Netsnmp_Node_Handler handle_locksPerTransaction;
Netsnmp_Node_Handler handle_locksInUse;
Netsnmp_Node_Handler handle_resourcesInUse;
Netsnmp_Node_Handler handle_lockListsInUse;
Netsnmp_Node_Handler handle_totalLockLists;
Netsnmp_Node_Handler handle_serverID;
Netsnmp_Node_Handler handle_avgRows;
Netsnmp_Node_Handler handle_listenFails;
Netsnmp_Node_Handler handle_selectsProcessed;
Netsnmp_Node_Handler handle_currentConnections;
Netsnmp_Node_Handler handle_highwaterConnections;
Netsnmp_Node_Handler handle_listenMask;
Netsnmp_Node_Handler handle_listenState;
Netsnmp_Node_Handler handle_shutdownState;
Netsnmp_Node_Handler handle_serverState;
Netsnmp_Node_Handler handle_serverStateMask;
Netsnmp_Node_Handler handle_server;
Netsnmp_Node_Handler handle_startupName;
Netsnmp_Node_Handler handle_serverName;
Netsnmp_Node_Handler handle_startupTime;
Netsnmp_Node_Handler handle_serverPID;
Netsnmp_Node_Handler handle_fastCommit;
Netsnmp_Node_Handler handle_psfMemory;

#endif                          /* INGRES_H */
