/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $ 
 *
 * $Id:$
 */
/*
 * standard Net-SNMP includes 
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/*
 * include our parent header 
 */
#include "dmfTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement dmfTable get routines.
 * TODO:240:M: Implement dmfTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dmfTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * INGRES-MIB::dmfTable is subid 1 of imadb.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.757.5.1.1, length: 10
 */

/*
 * ---------------------------------------------------------------------
 * * TODO:200:r: Implement dmfTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param serverName_ptr
 * @param serverName_ptr_len
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
dmfTable_indexes_set_tbl_idx(dmfTable_mib_index * tbl_idx,
                             char *serverName_val_ptr,
                             size_t serverName_val_ptr_len)
{
    DEBUGMSGTL(("verbose:dmfTable:dmfTable_indexes_set_tbl_idx",
                "called\n"));
    DEBUGMSGTL(("verbose:dmfTable","serverName %s\n",serverName_val_ptr));

    /*
     * serverName(1)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h 
     */


    tbl_idx->serverName_len = sizeof(tbl_idx->serverName) / sizeof(tbl_idx->serverName[0]);     /* max length */


    /*
     * make sure there is enough space for serverName data
     */
    if ((NULL == tbl_idx->serverName) ||
        (tbl_idx->serverName_len < (serverName_val_ptr_len))) {
        snmp_log(LOG_ERR, "not enough space for value\n");
        return MFD_ERROR;
    }
    tbl_idx->serverName_len = serverName_val_ptr_len;
    memcpy(tbl_idx->serverName, serverName_val_ptr,
           serverName_val_ptr_len * sizeof(serverName_val_ptr[0]));


    return MFD_SUCCESS;
}                               /* dmfTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
dmfTable_indexes_set(dmfTable_rowreq_ctx * rowreq_ctx,
                     char *serverName_val_ptr,
                     size_t serverName_val_ptr_len)
{
    DEBUGMSGTL(("verbose:dmfTable:dmfTable_indexes_set", "called\n"));

    if (MFD_SUCCESS !=
        dmfTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx,
                                     serverName_val_ptr,
                                     serverName_val_ptr_len))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if (0 != dmfTable_index_to_oid(&rowreq_ctx->oid_idx,
                                   &rowreq_ctx->tbl_idx)) {
	DEBUGMSGTL(("verbose:dmfTable","not equal 0\n"));
        return MFD_ERROR;
    }
	DEBUGMSGTL(("verbose:dmfTable","MFD_SUCCESS\n"));
    return MFD_SUCCESS;
}                               /* dmfTable_indexes_set */


/*---------------------------------------------------------------------
 * INGRES-MIB::dmfEntry.processID
 * processID is subid 2 of dmfEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.757.5.1.1.1.2
 * Description:
Please replace this text with your description.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is OCTETSTR (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.
 */
/**
 * Extract the current value of the processID data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param processID_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param processID_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by processID.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*processID_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update processID_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
processID_get(dmfTable_rowreq_ctx * rowreq_ctx,
              char **processID_val_ptr_ptr,
              size_t *processID_val_ptr_len_ptr)
{
   /** we should have a non-NULL pointer and enough storage */
    netsnmp_assert((NULL != processID_val_ptr_ptr)
                   && (NULL != *processID_val_ptr_ptr));
    netsnmp_assert(NULL != processID_val_ptr_len_ptr);


    DEBUGMSGTL(("verbose:dmfTable:processID_get", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:231:o: |-> Extract the current value of the processID data.
     * copy (* processID_val_ptr_ptr ) data and (* processID_val_ptr_len_ptr ) from rowreq_ctx->data
     */
    /*
     * make sure there is enough space for processID data
     */
    if ((NULL == (*processID_val_ptr_ptr)) ||
        ((*processID_val_ptr_len_ptr) <
         (rowreq_ctx->data.processID_len *
          sizeof(rowreq_ctx->data.processID[0])))) {
        /*
         * allocate space for processID data
         */
        (*processID_val_ptr_ptr) =
            malloc(rowreq_ctx->data.processID_len *
                   sizeof(rowreq_ctx->data.processID[0]));
        if (NULL == (*processID_val_ptr_ptr)) {
            snmp_log(LOG_ERR, "could not allocate memory\n");
            return MFD_ERROR;
        }
    }
    (*processID_val_ptr_len_ptr) =
        rowreq_ctx->data.processID_len *
        sizeof(rowreq_ctx->data.processID[0]);
    memcpy((*processID_val_ptr_ptr), rowreq_ctx->data.processID,
           rowreq_ctx->data.processID_len *
           sizeof(rowreq_ctx->data.processID[0]));

    return MFD_SUCCESS;
}                               /* processID_get */



/** @} */
