# include "/opt/Ingres/IngresII/ingres/files/eqdef.h"
/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $ 
 *
 * $Id:$
 */
/*
 * standard Net-SNMP includes 
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
/*
 * include our parent header 
 */
#include "dmfTable.h"
#include "dmfTable_data_access.h"
# include "/opt/Ingres/IngresII/ingres/files/eqsqlca.h"
    extern IISQLCA sqlca;   /* SQL Communications Area */
close_down(){
exit(-1);
}
/** @ingroup interface
 * @addtogroup data_access data_access: Routines to access data
 *
 * These routines are used to locate the data used to satisfy
 * requests.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dmfTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * INGRES-MIB::dmfTable is subid 1 of imadb.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.757.5.1.1, length: 10
 */
/**
 * initialization for dmfTable data access
 *
 * This function is called during startup to allow you to
 * allocate any resources you need for the data table.
 *
 * @param dmfTable_reg
 *        Pointer to dmfTable_registration
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : unrecoverable error.
 */
int
dmfTable_init_data(dmfTable_registration * dmfTable_reg)
{
    DEBUGMSGTL(("verbose:dmfTable:dmfTable_init_data", "called\n"));
    /*
     * TODO:303:o: Initialize dmfTable data.
     */
    /*
     ***************************************************
     ***             START EXAMPLE CODE              ***
     ***---------------------------------------------***/
    /*
     * if you are the sole writer for the file, you could
     * open it here. However, as stated earlier, we are assuming
     * the worst case, which in this case means that the file is
     * written to by someone else, and might not even exist when
     * we start up. So we can't do anything here.
     */
    /*
     ***---------------------------------------------***
     ***              END  EXAMPLE CODE              ***
     ***************************************************/
    return MFD_SUCCESS;
}                               /* dmfTable_init_data */
/**
 * container overview
 *
 */
/**
 * container initialization
 *
 * @param container_ptr_ptr A pointer to a container pointer. If you
 *        create a custom container, use this parameter to return it
 *        to the MFD helper. If set to NULL, the MFD helper will
 *        allocate a container for you.
 * @param  cache A pointer to a cache structure. You can set the timeout
 *         and other cache flags using this pointer.
 *
 *  This function is called at startup to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases. If no custom
 *  container is allocated, the MFD code will create one for your.
 *
 *  This is also the place to set up cache behavior. The default, to
 *  simply set the cache timeout, will work well with the default
 *  container. If you are using a custom container, you may want to
 *  look at the cache helper documentation to see if there are any
 *  flags you want to set.
 *
 * @remark
 *  This would also be a good place to do any initialization needed
 *  for you data source. For example, opening a connection to another
 *  process that will supply the data, opening a database, etc.
 */
void
dmfTable_container_init(netsnmp_container ** container_ptr_ptr,
                        netsnmp_cache * cache)
{
    DEBUGMSGTL(("verbose:dmfTable:dmfTable_container_init", "called\n"));
    if (NULL == container_ptr_ptr) {
        snmp_log(LOG_ERR,
                 "bad container param to dmfTable_container_init\n");
        return;
    }
    /*
     * For advanced users, you can use a custom container. If you
     * do not create one, one will be created for you.
     */
    *container_ptr_ptr = NULL;
    if (NULL == cache) {
        snmp_log(LOG_ERR, "bad cache param to dmfTable_container_init\n");
        return;
    }
    /*
     * TODO:345:A: Set up dmfTable cache properties.
     *
     * Also for advanced users, you can set parameters for the
     * cache. Do not change the magic pointer, as it is used
     * by the MFD helper. To completely disable caching, set
     * cache->enabled to 0.
     */
    cache->timeout = DMFTABLE_CACHE_TIMEOUT;    /* seconds */
}                               /* dmfTable_container_init */
/**
 * container shutdown
 *
 * @param container_ptr A pointer to the container.
 *
 *  This function is called at shutdown to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases.
 *
 *  This function is called before dmfTable_container_free().
 *
 * @remark
 *  This would also be a good place to do any cleanup needed
 *  for you data source. For example, closing a connection to another
 *  process that supplied the data, closing a database, etc.
 */
void
dmfTable_container_shutdown(netsnmp_container * container_ptr)
{
    DEBUGMSGTL(("verbose:dmfTable:dmfTable_container_shutdown",
                "called\n"));
    if (NULL == container_ptr) {
        snmp_log(LOG_ERR, "bad params to dmfTable_container_shutdown\n");
        return;
    }
}                               /* dmfTable_container_shutdown */
/**
 * load initial data
 *
 * TODO:350:M: Implement dmfTable data load
 * This function will also be called by the cache helper to load
 * the container again (after the container free function has been
 * called to free the previous contents).
 *
 * @param container container to which items should be inserted
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_RESOURCE_UNAVAILABLE : Can't access data source
 * @retval MFD_ERROR                : other error.
 *
 *  This function is called to load the index(es) (and data, optionally)
 *  for the every row in the data set.
 *
 * @remark
 *  While loading the data, the only important thing is the indexes.
 *  If access to your data is cheap/fast (e.g. you have a pointer to a
 *  structure in memory), it would make sense to update the data here.
 *  If, however, the accessing the data invovles more work (e.g. parsing
 *  some other existing data, or peforming calculations to derive the data),
 *  then you can limit yourself to setting the indexes and saving any
 *  information you will need later. Then use the saved information in
 *  dmfTable_row_prep() for populating data.
 *
 * @note
 *  If you need consistency between rows (like you want statistics
 *  for each row to be from the same time frame), you should set all
 *  data here.
 *
 */
int
dmfTable_container_load(netsnmp_container * container)
{
    dmfTable_rowreq_ctx *rowreq_ctx;
    size_t          count = 0;
    /*
     * temporary storage for index values
     */
    /*
     * serverName(1)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
     */
        /** 128 - 1(entry) - 1(col) - 0(other indexes) = 114 */
    char            serverName[114];
    size_t          serverName_len;
    char            processID[65];
    size_t          processID_len;
        char    server[65];
    	size_t  server_len;
        long    pagesize;
    /*
     * this example code is based on a data source that is a
     * text file to be read and parsed.
     */
    FILE           *filep;
    char            line[MAX_LINE_SIZE];
# include "ima/dmfcache.c"
/* # line 255 "dmfTable_data_access.sc" */	/* host code */
    DEBUGMSGTL(("verbose:dmfTable:dmfTable_container_load", "called\n"));
    /*
     ***************************************************
     ***             START EXAMPLE CODE              ***
     ***---------------------------------------------***/
    /*
     * open our data file.
     */
/* # line 266 "dmfTable_data_access.sc" */	/* connect */
  {
    IIsqInit(&sqlca);
    IIsqConnect(0,(char *)"imadb",(char *)0, (char *)0, (char *)0, (char *)0, 
    (char *)0, (char *)0, (char *)0, (char *)0, (char *)0, (char *)0, 
    (char *)0, (char *)0, (char *)0);
    if (sqlca.sqlcode < 0) 
      IIsqStop(&sqlca);
  }
/* # line 268 "dmfTable_data_access.sc" */	/* host code */
	DEBUGMSGTL(("verbose:dmfTable","Connected to database\n"));
    filep = fopen("/etc/dummy.conf", "r");
    if (NULL == filep) {
        return MFD_RESOURCE_UNAVAILABLE;
    }
    /*
     ***---------------------------------------------***
     ***              END  EXAMPLE CODE              ***
     ***************************************************/
    /*
     * TODO:351:M: |-> Load/update data in the dmfTable container.
     * loop over your dmfTable data, allocate a rowreq context,
     * set the index(es) [and data, optionally] and insert into
     * the container.
     */
/* # line 286 "dmfTable_data_access.sc" */	/* open */
  {
    IIsqInit(&sqlca);
    IIcsOpen((char *)"dmfcsr",15911,17405);
    IIwritio(0,(short *)0,1,32,0,(char *)
"select * from ima_dmf_cache_stats");
    IIwritio(0,(short *)0,1,32,0,(char *)" for readonly ");
    IIcsQuery((char *)"dmfcsr",15911,17405);
    if (sqlca.sqlcode < 0) 
      IIsqStop(&sqlca);
  }
/* # line 287 "dmfTable_data_access.sc" */	/* host code */
	DEBUGMSGTL(("verbose:dmfTable","Cursor opened\n"));
    while (1) {
/* # line 292 "dmfTable_data_access.sc" */	/* host code */
//allows break out of 'do' loop
        do {
/* # line 295 "dmfTable_data_access.sc" */	/* fetch */
  {
    IIsqInit(&sqlca);
    if (IIcsRetScroll((char *)"dmfcsr",15911,17405,0,0) != 0) {
      IIcsGetio((short *)0,1,32,64,(dmfrec).server);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).page_size),&(dmfrec).page_size);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).force_count),&
      (dmfrec).force_count);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).io_wait_count),&
      (dmfrec).io_wait_count);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).group_buffer_read_count),&
      (dmfrec).group_buffer_read_count);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).group_buffer_write_count),&
      (dmfrec).group_buffer_write_count);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).fix_count),&(dmfrec).fix_count);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).unfix_count),&
      (dmfrec).unfix_count);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).read_count),&
      (dmfrec).read_count);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).write_count),&
      (dmfrec).write_count);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).hit_count),&(dmfrec).hit_count);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).dirty_unfix_count),&
      (dmfrec).dirty_unfix_count);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).pages_still_valid),&
      (dmfrec).pages_still_valid);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).pages_invalid),&
      (dmfrec).pages_invalid);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).buffer_count),&
      (dmfrec).buffer_count);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).page_buffer_count),&
      (dmfrec).page_buffer_count);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).flimit),&(dmfrec).flimit);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).mlimit),&(dmfrec).mlimit);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).wbstart),&(dmfrec).wbstart);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).wbend),&(dmfrec).wbend);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).hash_bucket_count),&
      (dmfrec).hash_bucket_count);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).group_buffer_count),&
      (dmfrec).group_buffer_count);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).group_buffer_size),&
      (dmfrec).group_buffer_size);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).cache_status),&
      (dmfrec).cache_status);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).free_buffer_count),&
      (dmfrec).free_buffer_count);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).free_buffer_waiters),&
      (dmfrec).free_buffer_waiters);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).fixed_buffer_count),&
      (dmfrec).fixed_buffer_count);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).modified_buffer_count),&
      (dmfrec).modified_buffer_count);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).free_group_buffer_count),&
      (dmfrec).free_group_buffer_count);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).fixed_group_buffer_count),&
      (dmfrec).fixed_group_buffer_count);
      IIcsGetio((short *)0,1,30,sizeof((dmfrec).modified_group_buffer_count),&
      (dmfrec).modified_group_buffer_count);
      IIcsERetrieve();
    } /* IIcsRetrieve */
    if (sqlca.sqlcode == 100) 
      goto close_dmfcsr;
    else if (sqlca.sqlcode < 0) 
      IIsqStop(&sqlca);
  }
/* # line 296 "dmfTable_data_access.sc" */	/* host code */
	DEBUGMSGTL(("verbose:dmfTable","SQL fetched\n"));
	DEBUGMSGTL(("verbose:dmfTable","Server %s\n",dmfrec.server));
	DEBUGMSGTL(("verbose:dmfTable","Page Size %d\n",dmfrec.page_size));
	DEBUGMSGTL(("verbose:dmfTable","Fix Count %d\n",dmfrec.fix_count));
        } while (sqlca.sqlcode == 0);
        /*
         * check for end of data
         */
	close_dmfcsr:
/* # line 308 "dmfTable_data_access.sc" */	/* close */
  {
    IIsqInit(&sqlca);
    IIcsClose((char *)"dmfcsr",15911,17405);
    if (sqlca.sqlcode < 0) 
      IIsqStop(&sqlca);
  }
/* # line 309 "dmfTable_data_access.sc" */	/* host code */
	break;
        /*
         * parse line into variables
         */
	strcpy(server,dmfrec.server);
	server_len = strlen(server);
	pagesize = dmfrec.page_size;
        /*
         ***---------------------------------------------***
         ***              END  EXAMPLE CODE              ***
         ***************************************************/
        /*
         * TODO:352:M: |   |-> set indexes in new dmfTable rowreq context.
         * data context will be set from the param (unless NULL,
         *      in which case a new data context will be allocated)
         */
        rowreq_ctx = dmfTable_allocate_rowreq_ctx(NULL);
        if (NULL == rowreq_ctx) {
            snmp_log(LOG_ERR, "memory allocation failed\n");
            return MFD_RESOURCE_UNAVAILABLE;
        }
        if (MFD_SUCCESS !=
            dmfTable_indexes_set(rowreq_ctx, server, server_len, pagesize)) {
            //dmfTable_indexes_set(rowreq_ctx, "server1", 7)) {
            snmp_log(LOG_ERR,
                     "error setting index while loading "
                     "dmfTable data.\n");
            dmfTable_release_rowreq_ctx(rowreq_ctx);
            continue;
        }
        /*
         * TODO:352:r: |   |-> populate dmfTable data context.
         * Populate data context here. (optionally, delay until row prep)
         */
	strncpy(rowreq_ctx->data.processID,"",1);;
	rowreq_ctx->data.processID_len = 65;
        /*
         * TRANSIENT or semi-TRANSIENT data:
         * copy data or save any info needed to do it in row_prep.
         */
        /*
         * setup/save data for processID
         * processID(2)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
         */
	strncpy(processID,line+8,10);
	processID_len = 10;
    /** no mapping */
        /*
         * make sure there is enough space for processID data
         */
	DEBUGMSGTL(("verbose:dmfTable","rowreq processID_len = %d\n",rowreq_ctx->data.processID_len));
	DEBUGMSGTL(("verbose:dmfTable","processID size = %d\n",(processID_len * sizeof(processID[0])) ));
        if ((NULL == rowreq_ctx->data.processID) ||
            (rowreq_ctx->data.processID_len <
             (processID_len * sizeof(processID[0])))) {
            snmp_log(LOG_ERR, "not enough space for data value\n");
            return MFD_ERROR;
        }
        rowreq_ctx->data.processID_len =
            processID_len * sizeof(processID[0]);
        memcpy(rowreq_ctx->data.processID, processID,
               processID_len * sizeof(processID[0]));
        /*
         * insert into table container
	 */
	CONTAINER_INSERT(container, rowreq_ctx);
        ++count;
    }
    /*
     ***************************************************
     ***             START EXAMPLE CODE              ***
     ***---------------------------------------------***/
    if (NULL != filep)
        fclose(filep);
    /*
     ***---------------------------------------------***
     ***              END  EXAMPLE CODE              ***
     ***************************************************/
    DEBUGMSGT(("verbose:dmfTable:dmfTable_container_load",
               "inserted %d records\n", count));
    return MFD_SUCCESS;
}                               /* dmfTable_container_load */
/**
 * container clean up
 *
 * @param container container with all current items
 *
 *  This optional callback is called prior to all
 *  item's being removed from the container. If you
 *  need to do any processing before that, do it here.
 *
 * @note
 *  The MFD helper will take care of releasing all the row contexts.
 *
 */
void
dmfTable_container_free(netsnmp_container * container)
{
    DEBUGMSGTL(("verbose:dmfTable:dmfTable_container_free", "called\n"));
    /*
     * TODO:380:M: Free dmfTable container data.
     */
}                               /* dmfTable_container_free */
/**
 * prepare row for processing.
 *
 *  When the agent has located the row for a request, this function is
 *  called to prepare the row for processing. If you fully populated
 *  the data context during the index setup phase, you may not need to
 *  do anything.
 *
 * @param rowreq_ctx pointer to a context.
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 */
int
dmfTable_row_prep(dmfTable_rowreq_ctx * rowreq_ctx)
{
    DEBUGMSGTL(("verbose:dmfTable:dmfTable_row_prep", "called\n"));
    netsnmp_assert(NULL != rowreq_ctx);
    /*
     * TODO:390:o: Prepare row for request.
     * If populating row data was delayed, this is the place to
     * fill in the row for this request.
     */
    return MFD_SUCCESS;
}                               /* dmfTable_row_prep */
/** @} */
