/* This file is automatically generated by configure.  Do not modify by hand. */
  if (should_init("dmfTable")) shutdown_dmfTable();
  if (should_init("notification_log")) shutdown_notification_log();
  if (should_init("snmpNotifyFilterTable")) shutdown_snmpNotifyFilterTable();
