/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $ 
 *
 * $Id:$
 */
/*
 * standard Net-SNMP includes 
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/*
 * include our parent header 
 */
#include "dmfTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement dmfTable get routines.
 * TODO:240:M: Implement dmfTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dmfTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * INGRES-MIB::dmfTable is subid 1 of imadb.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.757.5.1.1, length: 10
 */

/*
 * ---------------------------------------------------------------------
 * * TODO:200:r: Implement dmfTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param server_ptr
 * @param server_ptr_len
 * @param pagesize_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
dmfTable_indexes_set_tbl_idx(dmfTable_mib_index * tbl_idx,
                             char *server_val_ptr,
                             size_t server_val_ptr_len, long pagesize_val)
{
    DEBUGMSGTL(("verbose:dmfTable:dmfTable_indexes_set_tbl_idx",
                "called\n"));

    /*
     * server(1)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h 
     */
    tbl_idx->server_len = sizeof(tbl_idx->server) / sizeof(tbl_idx->server[0]); /* max length */
    /*
     * make sure there is enough space for server data
     */
    if ((NULL == tbl_idx->server) ||
        (tbl_idx->server_len < (server_val_ptr_len))) {
        snmp_log(LOG_ERR, "not enough space for value\n");
        return MFD_ERROR;
    }
    tbl_idx->server_len = server_val_ptr_len;
    memcpy(tbl_idx->server, server_val_ptr,
           server_val_ptr_len * sizeof(server_val_ptr[0]));

    /*
     * pagesize(2)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h 
     */
    tbl_idx->pagesize = pagesize_val;


    return MFD_SUCCESS;
}                               /* dmfTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
dmfTable_indexes_set(dmfTable_rowreq_ctx * rowreq_ctx,
                     char *server_val_ptr, size_t server_val_ptr_len,
                     long pagesize_val)
{
    DEBUGMSGTL(("verbose:dmfTable:dmfTable_indexes_set", "called\n"));

    if (MFD_SUCCESS !=
        dmfTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx, server_val_ptr,
                                     server_val_ptr_len, pagesize_val))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if (0 != dmfTable_index_to_oid(&rowreq_ctx->oid_idx,
                                   &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
}                               /* dmfTable_indexes_set */


/*---------------------------------------------------------------------
 * INGRES-MIB::dmfEntry.fixCount
 * fixCount is subid 3 of dmfEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.757.5.1.1.1.3
 * Description:
Please replace this text with your description.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the fixCount data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param fixCount_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
fixCount_get(dmfTable_rowreq_ctx * rowreq_ctx, long *fixCount_val_ptr)
{
   /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != fixCount_val_ptr);


    DEBUGMSGTL(("verbose:dmfTable:fixCount_get", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:231:o: |-> Extract the current value of the fixCount data.
     * copy (* fixCount_val_ptr ) from rowreq_ctx->data
     */
    (*fixCount_val_ptr) = rowreq_ctx->data.fixCount;

    return MFD_SUCCESS;
}                               /* fixCount_get */



/** @} */
