/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-oids.m2c 12855 2005-09-27 15:56:08Z rstory $
 *
 * $Id:$
 */
#ifndef DMFTABLE_OIDS_H
#define DMFTABLE_OIDS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     * column number definitions for table dmfTable 
     */
#define DMFTABLE_OID              1,3,6,1,4,1,757,5,1,1

#define COLUMN_SERVER         1

#define COLUMN_PAGESIZE         2

#define COLUMN_FIXCOUNT         3


#define DMFTABLE_MIN_COL   COLUMN_SERVER
#define DMFTABLE_MAX_COL   COLUMN_FIXCOUNT



#ifdef __cplusplus
}
#endif
#endif                          /* DMFTABLE_OIDS_H */
