/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $
 *
 * $Id:$
 *
 * @file dmfTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef DMFTABLE_DATA_GET_H
#define DMFTABLE_DATA_GET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * GET function declarations
     */

    /*
     *********************************************************************
     * GET Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dmfTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * INGRES-MIB::dmfTable is subid 1 of imadb.
     * Its status is Current.
     * OID: .1.3.6.1.4.1.757.5.1.1, length: 10
     */
    /*
     * indexes
     */

    int             fixCount_get(dmfTable_rowreq_ctx * rowreq_ctx,
                                 long *fixCount_val_ptr);


    int             dmfTable_indexes_set_tbl_idx(dmfTable_mib_index *
                                                 tbl_idx,
                                                 char *server_val_ptr,
                                                 size_t server_val_ptr_len,
                                                 long pagesize_val);
    int             dmfTable_indexes_set(dmfTable_rowreq_ctx * rowreq_ctx,
                                         char *server_val_ptr,
                                         size_t server_val_ptr_len,
                                         long pagesize_val);




#ifdef __cplusplus
}
#endif
#endif                          /* DMFTABLE_DATA_GET_H */
/** @} */
